name: Lint & Build - 'iugocare-client'

on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: yarn install, lint, and build
      run: |
        yarn install
        yarn run lint
        yarn run build --if-present
